export enum AuditLogType {
  INVENTORY = 'INVENTORY',
  ORDER = 'ORDER',
}

export enum AuditLogAction {
  STOCK_IN = 'STOCK_IN',
  ADJUSTMENT = 'ADJUSTMENT',
  TRANSFER_OUT = 'TRANSFER_OUT',
  TRANSFER_IN = 'TRANSFER_IN',
  STATUS_CHANGED = 'STATUS_CHANGED',
  MARKED_FREE = 'MARKED_FREE',
  UNMARKED_FREE = 'UNMARKED_FREE',
}

export interface AuditLog {
  id: number;
  shop_id: number | null;
  shop_name: string | null;
  user_id: number;
  user_name: string;
  type: AuditLogType;
  action: AuditLogAction;
  entity_type: string;
  entity_id: number;
  // Non-null only for logs generated by a receipt (creation, MARKED_FREE, UNMARKED_FREE).
  receipt_id: number | null;
  quantity: number | null;
  // Line revenue (quantity × price) for MARKED_FREE / UNMARKED_FREE rows, where quantity is always null.
  // Comes back as a numeric string (e.g. "24.99"), same as ReceiptItem.price — coerce with Number() before formatting.
  amount: number | string | null;
  notes: string | null;
  created_at: string;
}

export interface AuditLogDetail extends AuditLog {
  product_name: string | null;
}

export interface AuditLogListParams {
  page?: number;
  limit?: number;
  shopId?: number;
  userId?: number;
  type?: AuditLogType;
  action?: AuditLogAction;
  entityType?: string;
  entityId?: number;
  // Fetch the full log trail (creation + free-toggle entries) for one receipt.
  receiptId?: number;
  fromDate?: string;
  toDate?: string;
}
