import {
  Apple,
  Baby,
  Banana,
  BatteryFull,
  Beef,
  Beer,
  BookOpen,
  Boxes,
  CakeSlice,
  Candy,
  Cherry,
  Cigarette,
  Coffee,
  Cookie,
  Croissant,
  CupSoda,
  Donut,
  Droplets,
  Egg,
  Fish,
  Flame,
  Gamepad2,
  Gift,
  GlassWater,
  Headphones,
  IceCreamCone,
  Leaf,
  Lightbulb,
  Lollipop,
  Milk,
  Package,
  PawPrint,
  Pill,
  Pizza,
  Plug,
  Popcorn,
  Salad,
  Sandwich,
  Scissors,
  Shirt,
  ShoppingBasket,
  Soup,
  Sparkles,
  SprayCan,
  Store,
  Tag,
  Wine,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

/**
 * Curated Lucide icons available for categories. The backend stores any Lucide
 * name (max 100 chars, not enum-validated); we render from this registry so the
 * client bundle stays tree-shaken — a namespace import of lucide-react would
 * ship the whole icon set. Names outside the registry fall back to Package.
 */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  Cigarette,
  Flame,
  CupSoda,
  Coffee,
  ShoppingBasket,
  Cookie,
  Candy,
  Popcorn,
  Package,
  Beer,
  Wine,
  Milk,
  GlassWater,
  Pizza,
  Sandwich,
  Croissant,
  Donut,
  CakeSlice,
  IceCreamCone,
  Lollipop,
  Apple,
  Banana,
  Cherry,
  Egg,
  Fish,
  Beef,
  Salad,
  Soup,
  Leaf,
  SprayCan,
  Droplets,
  Sparkles,
  Shirt,
  Baby,
  PawPrint,
  Pill,
  Lightbulb,
  Plug,
  BatteryFull,
  Headphones,
  Gamepad2,
  BookOpen,
  Scissors,
  Gift,
  Tag,
  Boxes,
  Store,
  Wrench,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export function getCategoryIcon(name?: string | null): LucideIcon {
  return (name && CATEGORY_ICONS[name]) || Package;
}
